In [4]:
import os
import json
import requests
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("../data/raw/election_by_county.csv")

df

,county_code,election_year,state,eligible_voters,number_voters,valid_votes,invalid_votes,turnout,cdu,csu,...,zentrum,election_date,area,population,flag_unsuccessful_naive_merge,total_votes,cdu_csu,far_right,far_left,far_left_w_linke
0,1001,1990,1,69563,50485,50036,449,0.725745,0.370533,0.0,...,0.0,1990-12-02,56.36,86600,NaN,50036,0.370533,0.014330,0.000000,0.004157
1,1001,1994,1,68987,52379,51823,556,0.759259,0.344191,0.0,...,0.0,1994-10-16,56.44,87900,NaN,51823,0.344191,0.009629,0.000289,0.013797
2,1001,1998,1,65755,50560,49862,698,0.768915,0.291565,0.0,...,0.0,1998-09-27,56.44,84700,NaN,49862,0.291565,0.020697,0.000000,0.018290
3,1001,2002,1,65740,49054,48553,501,0.746182,0.295800,0.0,...,0.0,2002-09-22,56.38,84700,NaN,48553,0.295800,0.004284,0.000000,0.017692
4,1001,2005,1,66970,49002,48235,767,0.731701,0.288380,0.0,...,0.0,2005-09-18,56.38,86100,NaN,48235,0.288380,0.008852,0.000705,0.064269
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,16074,2025,16,65981,55149,54806,343,0.835832,0.196183,0.0,...,NaN,2025-02-23,815.24,82513,0.0,54806,0.196183,0.386764,0.000839,0.144273
3996,16075,2025,16,63125,51544,51203,341,0.816539,0.174951,0.0,...,NaN,2025-02-23,1151.30,79030,0.0,51203,0.174951,0.460598,0.000957,0.128137
3997,16076,2025,16,77827,63523,63045,478,0.816208,0.189547,0.0,...,NaN,2025-02-23,845.98,96102,0.0,63045,0.189547,0.437148,0.000952,0.122532
3998,16077,2025,16,70997,55631,55172,459,0.783568,0.173675,0.0,...,NaN,2025-02-23,569.39,87807,0.0,55172,0.173675,0.457623,0.001160,0.119481
3999,11000,2021,11,2468919,1856903,1826581,30322,0.752112,0.158597,0.0,...,0.0,2021-09-26,891.12,3677472,0.0,1826581,0.158597,0.085227,0.001823,0.116273

In [6]:
def afd_in_election(df, year):
    df_year = df[df['election_year'] == year].copy()
    df_year['afd_votes'] = (df_year['afd'] / 100) * df_year['valid_votes']
    state_afd = df_year.groupby('state').agg({
        'afd_votes': 'sum',
        'valid_votes': 'sum'
    }).reset_index()
    state_afd['afd_share_pct'] = (state_afd['afd_votes'] / state_afd['valid_votes']) * 100
    
    return state_afd

In [7]:
afd_2017 = afd_in_election(df, 2017)
afd_2021 = afd_in_election(df, 2021)
afd_2025 = afd_in_election(df, 2025)

In [8]:
afd_2017['year'] = 2017
afd_2021['year'] = 2021
afd_2025['year'] = 2025

In [9]:
afd_panel = pd.concat([afd_2017, afd_2021, afd_2025], ignore_index=True)

In [10]:
afd_panel

    state     afd_votes  valid_votes  afd_share_pct  year
0       1   1403.620000      1715641       0.081813  2017
1       2    765.110000       978118       0.078223  2017
2       3   4223.620000      4646976       0.090890  2017
3       4    332.440000       332323       0.100035  2017
4       5   9284.250000      9853377       0.094224  2017
5       6   3987.981654      3348900       0.119083  2017
6       7   2656.880000      2362506       0.112460  2017
7       8   7304.990000      5992968       0.121893  2017
8       9   9164.581794      7393210       0.123959  2017
9      10    589.200000       585258       0.100674  2017
10     11   2253.144198      1869042       0.120551  2017
11     12   3011.030000      1490831       0.201970  2017
12     13   1724.090000       927510       0.185884  2017
13     14   6709.237110      2479404       0.270599  2017
14     15   2444.010000      1244980       0.196309  2017
15     16   2940.690141      1294448       0.227177  2017
16      1   1195.660000      1762754       0.067829  2021
17      2    505.370000      1005544       0.050258  2021
18      3   3364.340000      4523221       0.074379  2021
19      4    225.750000       328040       0.068818  2021
20      5   7181.995676      9888030       0.072633  2021
21      6   2909.780000      3300810       0.088154  2021
22      7   2152.050000      2334152       0.092198  2021
23      8   5713.360000      5949660       0.096028  2021
24      9   6799.150000      7571313       0.089801  2021
25     10    576.290000       573668       0.100457  2021
26     11   1536.940000      1826581       0.084143  2021
27     12   2774.120000      1529643       0.181357  2021
28     13   1653.420000       918859       0.179943  2021
29     14   6070.440000      2462897       0.246476  2021
30     15   2354.920000      1201940       0.195927  2021
31     16   3032.330000      1264911       0.239727  2021
32      1   3061.650000      1880005       0.162853  2025
33      2   1136.080000      1045620       0.108651  2025
34      3   8945.400000      5015336       0.178361  2025
35      4    524.960000       348256       0.150740  2025
36      5  17703.790000     10526134       0.168189  2025
37      6   6367.780000      3580834       0.177830  2025
38      7   4986.950000      2482358       0.200896  2025
39      8  12564.300000      6349998       0.197863  2025
40      9  15157.310000      7972054       0.190131  2025
41     10   1292.940000       599723       0.215590  2025
42     11   2969.900000      1949533       0.152339  2025
43     12   5352.750000      1647338       0.324933  2025
44     13   3573.610000      1021242       0.349928  2025
45     14   9584.010000      2569572       0.372981  2025
46     15   4961.100000      1337349       0.370965  2025
47     16   5105.270000      1324160       0.385548  2025

In [11]:
state_mapping = {
    1: 'Schleswig-Holstein',
    2: 'Hamburg',
    3: 'Niedersachsen',
    4: 'Bremen',
    5: 'Nordrhein-Westfalen',
    6: 'Hessen',
    7: 'Rheinland-Pfalz',
    8: 'Baden-Württemberg',
    9: 'Bayern',
    10: 'Saarland',
    11: 'Berlin',
    12: 'Brandenburg',
    13: 'Mecklenburg-Vorpommern',
    14: 'Sachsen',
    15: 'Sachsen-Anhalt',
    16: 'Thüringen'
}

In [12]:
afd_panel['state_name'] = afd_panel['state'].map(state_mapping)

In [13]:
afd_panel

,state,afd_votes,valid_votes,afd_share_pct,year,state_name
0,1,1403.620000,1715641,0.081813,2017,Schleswig-Holstein
1,2,765.110000,978118,0.078223,2017,Hamburg
2,3,4223.620000,4646976,0.090890,2017,Niedersachsen
3,4,332.440000,332323,0.100035,2017,Bremen
4,5,9284.250000,9853377,0.094224,2017,Nordrhein-Westfalen
5,6,3987.981654,3348900,0.119083,2017,Hessen
6,7,2656.880000,2362506,0.112460,2017,Rheinland-Pfalz
7,8,7304.990000,5992968,0.121893,2017,Baden-Württemberg
8,9,9164.581794,7393210,0.123959,2017,Bayern
9,10,589.200000,585258,0.100674,2017,Saarland
10,11,2253.144198,1869042,0.120551,2017,Berlin
11,12,3011.030000,1490831,0.201970,2017,Brandenburg
12,13,1724.090000,927510,0.185884,2017,Mecklenburg-Vorpommern
13,14,6709.237110,2479404,0.270599,2017,Sachsen
14,15,2444.010000,1244980,0.196309,2017,Sachsen-Anhalt
15,16,2940.690141,1294448,0.227177,2017,Thüringen
16,1,1195.660000,1762754,0.067829,2021,Schleswig-Holstein
17,2,505.370000,1005544,0.050258,2021,Hamburg
18,3,3364.340000,4523221,0.074379,2021,Niedersachsen
19,4,225.750000,328040,0.068818,2021,Bremen
20,5,7181.995676,9888030,0.072633,2021,Nordrhein-Westfalen
21,6,2909.780000,3300810,0.088154,2021,Hessen
22,7,2152.050000,2334152,0.092198,2021,Rheinland-Pfalz
23,8,5713.360000,5949660,0.096028,2021,Baden-Württemberg
24,9,6799.150000,7571313,0.089801,2021,Bayern
25,10,576.290000,573668,0.100457,2021,Saarland
26,11,1536.940000,1826581,0.084143,2021,Berlin
27,12,2774.120000,1529643,0.181357,2021,Brandenburg
28,13,1653.420000,918859,0.179943,2021,Mecklenburg-Vorpommern
29,14,6070.440000,2462897,0.246476,2021,Sachsen
30,15,2354.920000,1201940,0.195927,2021,Sachsen-Anhalt
31,16,3032.330000,1264911,0.239727,2021,Thüringen
32,1,3061.650000,1880005,0.162853,2025,Schleswig-Holstein
33,2,1136.080000,1045620,0.108651,2025,Hamburg
34,3,8945.400000,5015336,0.178361,2025,Niedersachsen
35,4,524.960000,348256,0.150740,2025,Bremen
36,5,17703.790000,10526134,0.168189,2025,Nordrhein-Westfalen
37,6,6367.780000,3580834,0.177830,2025,Hessen
38,7,4986.950000,2482358,0.200896,2025,Rheinland-Pfalz
39,8,12564.300000,6349998,0.197863,2025,Baden-Württemberg
40,9,15157.310000,7972054,0.190131,2025,Bayern
41,10,1292.940000,599723,0.215590,2025,Saarland
42,11,2969.900000,1949533,0.152339,2025,Berlin
43,12,5352.750000,1647338,0.324933,2025,Brandenburg
44,13,3573.610000,1021242,0.349928,2025,Mecklenburg-Vorpommern
45,14,9584.010000,2569572,0.372981,2025,Sachsen
46,15,4961.100000,1337349,0.370965,2025,Sachsen-Anhalt
47,16,5105.270000,1324160,0.385548,2025,Thüringen

In [17]:
afd_panel.to_csv('../data/processed/afd_election_by_state.csv', index=False)