In [1]:
import os
import json
import requests
import pandas as pd
import numpy as np

In [17]:
df = pd.read_csv("../data/raw/election_by_county.csv")

df

,county_code,election_year,state,eligible_voters,number_voters,valid_votes,invalid_votes,turnout,cdu,csu,...,zentrum,election_date,area,population,flag_unsuccessful_naive_merge,total_votes,cdu_csu,far_right,far_left,far_left_w_linke
0,1001,1990,1,69563,50485,50036,449,0.725745,0.370533,0.0,...,0.0,1990-12-02,56.36,86600,NaN,50036,0.370533,0.014330,0.000000,0.004157
1,1001,1994,1,68987,52379,51823,556,0.759259,0.344191,0.0,...,0.0,1994-10-16,56.44,87900,NaN,51823,0.344191,0.009629,0.000289,0.013797
2,1001,1998,1,65755,50560,49862,698,0.768915,0.291565,0.0,...,0.0,1998-09-27,56.44,84700,NaN,49862,0.291565,0.020697,0.000000,0.018290
3,1001,2002,1,65740,49054,48553,501,0.746182,0.295800,0.0,...,0.0,2002-09-22,56.38,84700,NaN,48553,0.295800,0.004284,0.000000,0.017692
4,1001,2005,1,66970,49002,48235,767,0.731701,0.288380,0.0,...,0.0,2005-09-18,56.38,86100,NaN,48235,0.288380,0.008852,0.000705,0.064269
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,16074,2025,16,65981,55149,54806,343,0.835832,0.196183,0.0,...,NaN,2025-02-23,815.24,82513,0.0,54806,0.196183,0.386764,0.000839,0.144273
3996,16075,2025,16,63125,51544,51203,341,0.816539,0.174951,0.0,...,NaN,2025-02-23,1151.30,79030,0.0,51203,0.174951,0.460598,0.000957,0.128137
3997,16076,2025,16,77827,63523,63045,478,0.816208,0.189547,0.0,...,NaN,2025-02-23,845.98,96102,0.0,63045,0.189547,0.437148,0.000952,0.122532
3998,16077,2025,16,70997,55631,55172,459,0.783568,0.173675,0.0,...,NaN,2025-02-23,569.39,87807,0.0,55172,0.173675,0.457623,0.001160,0.119481
3999,11000,2021,11,2468919,1856903,1826581,30322,0.752112,0.158597,0.0,...,0.0,2021-09-26,891.12,3677472,0.0,1826581,0.158597,0.085227,0.001823,0.116273

In [14]:
df_2017 = df[df['election_year'] == 2017].copy()

df_2017

,county_code,election_year,state,eligible_voters,number_voters,valid_votes,invalid_votes,turnout,cdu,csu,...,zentrum,election_date,area,population,flag_unsuccessful_naive_merge,total_votes,cdu_csu,far_right,far_left,far_left_w_linke
7,1001,2017,1,70105,49694,49271,423,0.708851,0.271600,0.0,...,0.0,2017-09-24,56.74,88500,NaN,49271,0.271600,0.077327,0.000406,0.116072
15,1002,2017,1,186988,138481,137368,1113,0.740588,0.258612,0.0,...,0.0,2017-09-24,118.65,247900,NaN,137368,0.258612,0.071057,0.001041,0.108046
23,1003,2017,1,166673,118981,117879,1102,0.713859,0.289348,0.0,...,0.0,2017-09-24,214.21,216300,NaN,117879,0.289348,0.091458,0.001340,0.098313
31,1004,2017,1,60378,40325,39861,464,0.667876,0.311257,0.0,...,0.0,2017-09-24,71.63,79300,NaN,39861,0.311257,0.109832,0.000778,0.071800
39,1051,2017,1,107148,78004,77337,667,0.728002,0.367224,0.0,...,0.0,2017-09-24,1428.17,133400,NaN,77337,0.367224,0.088690,0.000504,0.062105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3167,16073,2017,16,90082,66164,65352,812,0.734486,0.263852,0.0,...,0.0,2017-09-24,1008.78,105158,NaN,65351,0.263852,0.284663,0.001576,0.165063
3175,16074,2017,16,68855,52933,52285,648,0.768760,0.300048,0.0,...,0.0,2017-09-24,815.26,83000,NaN,52285,0.300048,0.244200,0.001262,0.169991
3183,16075,2017,16,68269,51372,50721,651,0.752494,0.285286,0.0,...,0.0,2017-09-24,1151.33,81500,NaN,50721,0.285286,0.277104,0.001360,0.166065
3191,16076,2017,16,84711,64361,63402,959,0.759771,0.301867,0.0,...,0.0,2017-09-24,845.95,99300,NaN,63402,0.301867,0.266506,0.000931,0.157787
3199,16077,2017,16,77281,55754,54846,908,0.721445,0.289173,0.0,...,0.0,2017-09-24,569.44,90700,NaN,54846,0.289173,0.286402,0.001258,0.162291

In [18]:
df_2017 = df[df['election_year'] == 2017].copy()


df_2017['afd_votes'] = (df_2017['afd'] / 100) * df_2017['valid_votes']

In [19]:
df_2017

,county_code,election_year,state,eligible_voters,number_voters,valid_votes,invalid_votes,turnout,cdu,csu,...,election_date,area,population,flag_unsuccessful_naive_merge,total_votes,cdu_csu,far_right,far_left,far_left_w_linke,afd_votes
7,1001,2017,1,70105,49694,49271,423,0.708851,0.271600,0.0,...,2017-09-24,56.74,88500,NaN,49271,0.271600,0.077327,0.000406,0.116072,37.020000
15,1002,2017,1,186988,138481,137368,1113,0.740588,0.258612,0.0,...,2017-09-24,118.65,247900,NaN,137368,0.258612,0.071057,0.001041,0.108046,95.240000
23,1003,2017,1,166673,118981,117879,1102,0.713859,0.289348,0.0,...,2017-09-24,214.21,216300,NaN,117879,0.289348,0.091458,0.001340,0.098313,104.610000
31,1004,2017,1,60378,40325,39861,464,0.667876,0.311257,0.0,...,2017-09-24,71.63,79300,NaN,39861,0.311257,0.109832,0.000778,0.071800,41.240000
39,1051,2017,1,107148,78004,77337,667,0.728002,0.367224,0.0,...,2017-09-24,1428.17,133400,NaN,77337,0.367224,0.088690,0.000504,0.062105,66.260000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3167,16073,2017,16,90082,66164,65352,812,0.734486,0.263852,0.0,...,2017-09-24,1008.78,105158,NaN,65351,0.263852,0.284663,0.001576,0.165063,176.342698
3175,16074,2017,16,68855,52933,52285,648,0.768760,0.300048,0.0,...,2017-09-24,815.26,83000,NaN,52285,0.300048,0.244200,0.001262,0.169991,122.780000
3183,16075,2017,16,68269,51372,50721,651,0.752494,0.285286,0.0,...,2017-09-24,1151.33,81500,NaN,50721,0.285286,0.277104,0.001360,0.166065,134.520000
3191,16076,2017,16,84711,64361,63402,959,0.759771,0.301867,0.0,...,2017-09-24,845.95,99300,NaN,63402,0.301867,0.266506,0.000931,0.157787,162.030000
3199,16077,2017,16,77281,55754,54846,908,0.721445,0.289173,0.0,...,2017-09-24,569.44,90700,NaN,54846,0.289173,0.286402,0.001258,0.162291,150.610000

In [20]:
state_afd_2017 = df_2017.groupby('state').agg({
    'afd_votes': 'sum',
    'valid_votes': 'sum'
}).reset_index()

state_afd_2017['afd_share_pct'] = (state_afd_2017['afd_votes'] / state_afd_2017['valid_votes']) * 100

In [21]:
state_afd_2017

    state    afd_votes  valid_votes  afd_share_pct
0       1  1403.620000      1715641       0.081813
1       2   765.110000       978118       0.078223
2       3  4223.620000      4646976       0.090890
3       4   332.440000       332323       0.100035
4       5  9284.250000      9853377       0.094224
5       6  3987.981654      3348900       0.119083
6       7  2656.880000      2362506       0.112460
7       8  7304.990000      5992968       0.121893
8       9  9164.581794      7393210       0.123959
9      10   589.200000       585258       0.100674
10     11  2253.144198      1869042       0.120551
11     12  3011.030000      1490831       0.201970
12     13  1724.090000       927510       0.185884
13     14  6709.237110      2479404       0.270599
14     15  2444.010000      1244980       0.196309
15     16  2940.690141      1294448       0.227177

In [ ]:
#check data validity, final result perfectly fits the general election data
total_afd = state_afd_2017['afd_votes'].sum()
total_valid = state_afd_2017['valid_votes'].sum()
national_avg = (total_afd / total_valid) * 100

print(national_avg)

0.12639848009415774